export const FRUIT_DATA = [
    { id: 1, name: "Apple" },
    { id: 2, name: "Banana" },
    { id: 3, name: "Cherry" },
    { id: 4, name: "Date" },
    { id: 5, name: "Elderberry" },
    { id: 6, name: "Fig" },
    { id: 7, name: "Grape" },
    { id: 8, name: "Honeydew" },
    { id: 9, name: "Icaco" },
    { id: 10, name: "Jackfruit" },
    { id: 11, name: "Kiwi" },
    { id: 12, name: "Lemon" },
    { id: 13, name: "Mango" },
    { id: 14, name: "Nectarine" },
    { id: 15, name: "Orange" },
    { id: 16, name: "Papaya" },
    { id: 17, name: "Quince" },
    { id: 18, name: "Raspberry" },
    { id: 19, name: "Strawberry" },
    { id: 20, name: "Tangerine" },
    { id: 21, name: "Ugli fruit" },
    { id: 22, name: "Vaccinium" },
    { id: 23, name: "Watermelon" },
    { id: 24, name: "Xigua" },
    { id: 25, name: "Yellow plum" },
    { id: 26, name: "Zucchini" },
    { id: 27, name: "Lychee" },
    { id: 28, name: "Mulberry" },
    { id: 29, name: "Nance" },
    { id: 30, name: "Olive" },
    { id: 31, name: "Peach" },
    { id: 32, name: "Quenepa" },
    { id: 33, name: "Rambutan" },
    { id: 34, name: "Sapodilla" },
    { id: 35, name: "Tomato" },
    { id: 36, name: "Uva" },
    { id: 37, name: "Voavanga" },
    { id: 38, name: "Walnut" },
    { id: 39, name: "Ximenia" },
    { id: 40, name: "Yuzu" },
];
